### ISSUE TITLE
ExtractUniqueValues AttributeError

### ISSUE THREAD

**Issue by theneedforsneed** [VirtualPlanetaryLaboratory/bigplanet#4]
Using the code found in Lecture 3, Slide 16 of the VPLanet Developer's Workshop Lectures, I receive the following error when trying to extract a unique value. This error occurs for both "earth_TCore_initial" and for "earth_40KPowerCore_final".

```
Traceback (most recent call last):
  File "/ParameterSweep/ParameterSweep.py", line 8, in <module>
    TCore_uniq = bp.ExtractUniqueValues(data, "earth_TCore_initial")
  File "/anaconda3/lib/python3.8/site-packages/bigplanet-1.0.2-py3.8.egg/bigplanet/bigplanet_module.py", line 267, in ExtractUniqueValues
    data.append((d.decode()))
AttributeError: 'numpy.float64' object has no attribute 'decode'
```

I'm using the version of bigplanet shipped with https://github.com/VirtualPlanetaryLaboratory/vplanet/commit/ab640af7d2bbf80c5ea647d5bf971e2ce2c40631. Code was complied using Anaconda 3.8.3 on an Ubuntu instance using WSL2 (Win10).

https://github.com/VirtualPlanetaryLaboratory/bigplanet/blob/d63a77d888b772a0915ea89097adb4ece2318ecf/bigplanet/bigplanet_module.py#L267

**Comment by caitlyn-wilhelm** [comment]
Thanks for making an issue! This issue should be resolved with the most recent version.
